services:
  server:
    image: test1
    networks:
      - mynetwork
    hostname: "server"
    command: cristian

  peer1:
    image: test1
    networks:
      - mynetwork
    hostname: ""
    command: cristian


networks:
  mynetwork: {}